name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 14 * * 3' # Run Wednesdays at 2pm EST

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        laravel: [ 11.*, 12.*, 13.*]
        dependency-version: [ lowest, stable ]
        php: [ 8.3, 8.4, 8.5 ]

    name: ${{ matrix.laravel }} on ${{ matrix.php }} (${{ matrix.dependency-version }} deps)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, libxml, mbstring
          coverage: pcov
          tools: composer:v2

      - name: Register composer cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        if: ${{ steps.composer-cache.outputs.dir != '' }}
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer require --no-interaction --prefer-dist --update-with-all-dependencies --prefer-${{ matrix.dependency-version }} "illuminate/support:${{ matrix.laravel }}"

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-html "${{ github.workspace }}/code-coverage"

      - name: Publish code coverage
        if: matrix.laravel == '13.*' && matrix.dependency-version == 'stable'
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: "${{github.workspace}}/code-coverage"
