name: Tests

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        laravel: [10, 11, 12]
        dependency-version: [lowest, stable]
        include:
          - laravel: 10
            testbench: 8
            php: 8.1
          - laravel: 11
            testbench: 9
            php: 8.3
          - laravel: 12
            testbench: 10
            php: 8.3

    name: ${{ matrix.laravel }}.x on ${{ matrix.php }} (${{ matrix.dependency-version }} deps)

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, libxml, mbstring
          coverage: pcov

      - name: Install dependencies
        run: composer update --prefer-${{ matrix.dependency-version }} --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        
      - name: Set Laravel version
        run: "composer require --dev laravel/framework:^${{ matrix.laravel }}.0 orchestra/testbench:^${{ matrix.testbench }}.0 --update-with-all-dependencies --prefer-${{ matrix.dependency-version }} --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist"

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover ${{ github.workspace }}/clover.xml

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: echo "ok"
          debug: true
          coverageLocations:
            "${{github.workspace}}/clover.xml:clover"
